# -*- coding: utf-8 -*-
"""ASSIGNMENT.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QQK4s_6NceYLQrQpAueRwiO12K6Bh6_z
"""

contacts = {}
def add_contact():
    name = input("Enter name: ")
    phone = input("Enter phone number: ")
    email = input("Enter email address: ")
    contacts[name] = {
        "phone": phone,
        "email": email
    }
    print("Contact added successfully!")
def search_contact():
    name = input("Enter name to search: ")
    if name in contacts:
        print("Name:", name)
        print("Phone:", contacts[name]["phone"])
        print("Email:", contacts[name]["email"])
    else:
        print("Contact not found!")
def view_contacts():
    if len(contacts) == 0:
        print("No contacts saved.")
    else:
        for name, details in contacts.items():
            print("Name:", name)
            print("Phone:", details["phone"])
            print("Email:", details["email"])
while True:
    print("1. Add Contact")
    print("2. Search Contact")
    print("3. View Contacts")
    print("4. Exit")
    choice = input("Enter your choice (1-4): ")
    if choice == "1":
        add_contact()
    elif choice == "2":
        search_contact()
    elif choice == "3":
        view_contacts()
    elif choice == "4":
        print("Thank you for using Contact Book!")
        break
    else:
        print("Invalid choice! Please enter 1-4.")