# -*- coding: utf-8 -*-
"""calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EK_Xj3qIBorgicy5OWRdA2Mg-Q-ybeTM
"""

# Simple Calculator

print("===== Simple Calculator =====")

num1 = float(input("Enter first number: "))
operator = input("Enter operator (+, -, *, /): ")
num2 = float(input("Enter second number: "))

if operator == "+":
    print("Result =", num1 + num2)

elif operator == "-":
    print("Result =", num1 - num2)

elif operator == "*":
    print("Result =", num1 * num2)

elif operator == "/":
    if num2 == 0:
        print("Error! Division by zero is not allowed.")
    else:
        print("Result =", num1 / num2)
else:
    print("Invalid operator! Please enter +, -, *, or /.")