# -*- coding: utf-8 -*-
"""Menu-Driven Calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OOgf_h4Xcr6JH29Uqm3oyqxQKjZTrVuj
"""

# Week 3 Assignment
# Menu-Driven Calculator

while True:

    # Display menu
    print("\n===== Calculator Menu =====")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")
    print("5. Exit")

    # Take user's choice
    choice = int(input("Enter your choice (1-5): "))

    # Exit the program
    if choice == 5:
        print("Thank you for using the calculator!")
        break

    # Take numbers as input
    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))

    # Perform operation
    if choice == 1:
        print("Result =", num1 + num2)

    elif choice == 2:
        print("Result =", num1 - num2)

    elif choice == 3:
        print("Result =", num1 * num2)

    elif choice == 4:
      if num2 == 0:
        print("Error! Division by zero is not allowed.")
      else:
        print("Result =", num1 / num2)

    else:
        print("Invalid choice! Please enter a number between 1 and 5.")