# -*- coding: utf-8 -*-
"""Temperature Converter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iKtuet5rhL_3Ob30dzsD6GtNI6IThg_r
"""

# Week 2 Assignment
# Temperature Converter (Celsius ↔ Fahrenheit)

# Display conversion options
print("Temperature Converter")
print("1. Celsius to Fahrenheit")
print("2. Fahrenheit to Celsius")

# Take user's choice
choice = int(input("Enter your choice (1 or 2): "))

# Celsius to Fahrenheit
if choice == 1:
    celsius = float(input("Enter temperature in Celsius: "))
    fahrenheit = (celsius * 9/5) + 32
    print("Temperature in Fahrenheit =", fahrenheit)

# Fahrenheit to Celsius
elif choice == 2:
    fahrenheit = float(input("Enter temperature in Fahrenheit: "))
    celsius = (fahrenheit - 32) * 5/9
    print("Temperature in Celsius =", celsius)

# Invalid choice
else:
    print("Invalid choice! Please enter 1 or 2.")