# -*- coding: utf-8 -*-
"""week 8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Gz82mvhV-QQ5EHebHH4D1j4QoWhDEW-
"""

import requests
# Function to convert currency
def convert_currency():
    try:
        # Get input from user
        source = input("Enter source currency (e.g. USD): ").upper()
        target = input("Enter target currency (e.g. EUR): ").upper()
        amount = float(input("Enter amount: "))
        # API URL
        url = f"https://api.frankfurter.dev/v2/rate/{source}/{target}"
        # Send request to API
        response = requests.get(url)
        # Check if request was successful
        if response.status_code != 200:
            print("Error: Invalid currency or API request failed.")
            return
        # Convert response into JSON
        data = response.json()
        # Get exchange rate from JSON
        rate = data["rate"]
        # Calculate converted amount
        converted_amount = amount * rate
        # Display result
        print("Currency Conversion")
        print("Source Currency:", source)
        print("Target Currency:", target)
        print("Exchange Rate:", rate)
        print("Amount:", amount)
        print("Converted Amount:", converted_amount)
    except ValueError:
        print("Error: Please enter a valid amount.")
    except requests.exceptions.RequestException:
        print("Error: Could not connect to the API.")
    except KeyError:
        print("Error: Invalid currency entered.")
# Main program
print(" Currency Converter ")
convert_currency()