# -*- coding: utf-8 -*-
"""week 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LWjHwX85Haxtb8z1I5buvpvPW_TJ-wBf
"""

# Parent class
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
# Method
    def display_info(self):
        print("Name:", self.name)
        print("Age:", self.age)
# Student class inherits from Person
class Student(Person):
    def __init__(self, student_id, name, age, course):
        super().__init__(name, age)
        self.student_id = student_id
        self.course = course
# Method overriding
    def display_info(self):
        print("Student ID:", self.student_id)
        print("Name:", self.name)
        print("Age:", self.age)
        print("Course/Program:", self.course)
# Student Management System class
class StudentManagementSystem:
    def __init__(self):
        self.students = {}
# Add student
    def add_student(self):
        student_id = input("Enter Student ID: ")
        name = input("Enter Student Name: ")
        age = int(input("Enter Age: "))
        course = input("Enter Course/Program: ")
        student = Student(student_id, name, age, course)
        self.students[student_id] = student
        print("Student added successfully!")
# Update student
    def update_student(self):
        student_id = input("Enter Student ID to update: ")
        if student_id in self.students:
            student = self.students[student_id]
            print("\nEnter new information:")
            student.name = input("Enter new name: ")
            student.age = int(input("Enter new age: "))
            student.course = input("Enter new course/program: ")
            print("Student updated successfully!")
        else:
            print("Student not found.")
# View all students
    def view_students(self):
        if len(self.students) == 0:
            print("No students registered.")
        else:
            print("Student Records")
            for student in self.students.values():
                student.display_info()
                print("--------------------------")
# Create object of StudentManagementSystem
system = StudentManagementSystem()
# Main menu
while True:
    print("Student Management System")
    print("1. Add Student")
    print("2. Update Student")
    print("3. View Students")
    print("4. Exit")
    choice = input("Enter your choice: ")
    if choice == "1":
        system.add_student()
    elif choice == "2":
        system.update_student()
    elif choice == "3":
        system.view_students()
    elif choice == "4":
        print("Program exited successfully.")
        break
    else:
        print("Invalid choice. Please try again.")