# -*- coding: utf-8 -*-
"""WEEK6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bT6SlxYOf8CYW57FDo4548HO6wDDpLiW
"""

import csv
FILE_NAME = "students.csv"
def calculate_grade(marks):
    if marks >= 90:
        return "A"
    elif marks >= 80:
        return "B"
    elif marks >= 70:
        return "C"
    elif marks >= 60:
        return "D"
    else:
        return "F"
def add_student():
    try:
        name = input("Enter student name: ")
        marks = float(input("Enter marks (0-100): "))
        if marks < 0 or marks > 100:
            raise ValueError("Marks must be between 0 and 100.")
        grade = calculate_grade(marks)
        with open(FILE_NAME, "a", newline="") as file:
            writer = csv.writer(file)
            if file.tell() == 0:
                writer.writerow(["Name", "Marks", "Grade"])
            writer.writerow([name, marks, grade])
        print("Student added successfully!")
    except ValueError as e:
        print("Error:", e)
    except PermissionError:
        print("Error: Permission denied. Cannot write to the file.")
    except Exception as e:
        print("An unexpected error occurred:", e)
def view_students():
    try:
        with open(FILE_NAME, "r", newline="") as file:
            reader = csv.DictReader(file)
            records = list(reader)
            if not records:
                print("No student records found.")
                return
            print("\n--- Student Records ---")
            for student in records:
                try:
                    name = student["Name"]
                    marks = float(student["Marks"])
                    grade = student["Grade"]
                    print(f"Name: {name} | Marks: {marks} | Grade: {grade}")
                except (KeyError, ValueError):
                    print("Error: Invalid data found in the CSV file.")
    except FileNotFoundError:
        print("Error: students.csv file not found.")
    except PermissionError:
        print("Error: Permission denied. Cannot read the file.")
    except Exception as e:
        print("An unexpected error occurred:", e)
def search_student():
    try:
        search_name = input("Enter student name to search: ")
        with open(FILE_NAME, "r", newline="") as file:
            reader = csv.DictReader(file)
            found = False
            for student in reader:
                try:
                    if student["Name"].lower() == search_name.lower():
                        marks = float(student["Marks"])
                        grade = calculate_grade(marks)
                        print("\nStudent Found!")
                        print("Name:", student["Name"])
                        print("Marks:", marks)
                        print("Grade:", grade)
                        found = True
                        break
                except (KeyError, ValueError):
                    print("Error: Invalid data found in the CSV file.")
                    return
            if not found:
                print("Student not found.")
    except FileNotFoundError:
        print("Error: students.csv file not found.")
    except PermissionError:
        print("Error: Permission denied. Cannot read the file.")
    except Exception as e:
        print("An unexpected error occurred:", e)
def main():
    while True:
        print("\n===== Student Gradebook Application =====")
        print("1. Add Student")
        print("2. View Student Records")
        print("3. Search Student")
        print("4. Exit")
        choice = input("Enter your choice: ")
        if choice == "1":
            add_student()
        elif choice == "2":
            view_students()
        elif choice == "3":
            search_student()
        elif choice == "4":
            print("Thank you for using the Student Gradebook Application!")
            break
        else:
            print("Invalid choice. Please enter 1, 2, 3, or 4.")
if __name__ == "__main__":
    main()